### ISSUE TITLE
Code review: address outstanding TODO's

### ISSUE THREAD

**Issue by toddmedema** [Fabricate-IO/expedition-cards#7]
- [x] clean up / combine / re-modularize cards + generate.js
- [x] improve how URL params are assigned and fetched. Make this bulletproof, b/c it's about to get a lot more complicated. Write test cases!
- [x] move demo code to separate repo: https://github.com/Fabricate-IO/expedition-demo
